variables:
  POSTGRES_HOST_AUTH_METHOD: trust
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

image: "harbor.hendrikx-itc.nl/1optic/rust-ci:1.69.0-buster"

default:
  cache:
    paths:
      - .cargo/
      - target/

stages:
  - test
  - build
  - build-image
  - deploy

# Use cargo to test the project
test-minerva-admin:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --package minerva-admin --verbose -- --format=json  -Z unstable-options --report-time | cargo2junit > results.xml
  artifacts:
    when: always
    reports:
      junit: results.xml

integration-test:cargo:
  stage: test
  services:
    - name: postgres:13
      alias: database
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --package minerva-admin
    - cargo build --package minerva-service
    - PGHOST=database PGUSER=postgres cargo test --package integration-tests --verbose -- --format=json  -Z unstable-options --report-time --test-threads=1 --nocapture | cargo2junit > results.xml
  artifacts:
    when: always
    reports:
      junit: results.xml

build-minerva-service:
  stage: build
  before_script:
    - apt-get update && apt-get install -y wget build-essential libssl-dev pkg-config openssh-client musl-tools
    - rustup target add x86_64-unknown-linux-musl
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --package minerva-service --release --target=x86_64-unknown-linux-musl
  artifacts:
    when: always
    paths:
      - target/x86_64-unknown-linux-musl/release/minerva-service

build-service-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${DOCKER_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_REGISTRY_USER}" "${DOCKER_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG

deploy:
  stage: deploy
  environment: production
  script:
    - curl --silent --fail ${DEPLOY_HOOK_URL}?version=${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG

